# -*- coding: utf-8 -*-
"""Copy of domain_aware_esm2_clinvar_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m7Lbqz7ihpysbkKTvpOSIifkS4EzMBWw
"""

# ============================================================
# 1. Install dependencies
# ============================================================
!pip -q install transformers accelerate biopython scikit-learn matplotlib pandas numpy requests tqdm

# ============================================================
# 2. Imports and global configuration
# ============================================================
import os
import re
import random
import urllib.request
import warnings
from collections import defaultdict

import numpy as np
import pandas as pd
import requests
import torch
from tqdm.auto import tqdm

from Bio.Align import substitution_matrices

from transformers import AutoTokenizer, AutoModel

from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score,
    precision_recall_fscore_support,
    roc_auc_score,
    classification_report,
    confusion_matrix,
    ConfusionMatrixDisplay,
    RocCurveDisplay,
)

import matplotlib.pyplot as plt

warnings.filterwarnings("ignore")

SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)

# Fallback if you get CUDA memory errors: "facebook/esm2_t6_8M_UR50D"
MODEL_NAME = "facebook/esm2_t12_35M_UR50D"

# Mutation-centered windows keep long proteins such as BRCA1/BRCA2/CFTR manageable.
WINDOW_RADIUS = 255          # gives a max local sequence length of 511 aa
MAX_TOKENS = 1024            # ESM-2 small models support around 1024 tokens
BATCH_SIZE = 8               # reduce to 2 or 4 if Colab runs out of memory

MAX_VARIANTS_PER_CLASS_PER_GENE = 120
MAX_VUS_CASE_STUDY_VARIANTS = 60

# A compact gene panel with many known missense variants.
# Values are UniProt canonical accessions.
TARGET_PROTEINS = {
    "TP53": "P04637",
    "PTEN": "P60484",
    "LDLR": "P01130",
    "CFTR": "P13569",
    "BRCA1": "P38398",
    "BRCA2": "P51587",
    "PAH": "P00439",
    "HBB": "P68871",
    "G6PD": "P11413",
}

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device:", device)
if device.type == "cuda":
    print("GPU:", torch.cuda.get_device_name(0))
print("Model:", MODEL_NAME)

# ============================================================
# 3. Download ClinVar variant summary
# ============================================================
CLINVAR_URL = "https://ftp.ncbi.nlm.nih.gov/pub/clinvar/tab_delimited/variant_summary.txt.gz"
CLINVAR_PATH = "/content/variant_summary.txt.gz"

if not os.path.exists(CLINVAR_PATH):
    print("Downloading ClinVar variant_summary.txt.gz ...")
    urllib.request.urlretrieve(CLINVAR_URL, CLINVAR_PATH)
else:
    print("ClinVar file already exists:", CLINVAR_PATH)

# Read only the header first so the code survives minor ClinVar column changes.
clinvar_header = pd.read_csv(CLINVAR_PATH, sep="\t", compression="gzip", nrows=0).columns.tolist()
print("Number of ClinVar columns:", len(clinvar_header))
print(clinvar_header[:12])

# ============================================================
# 4. Helper functions for parsing ClinVar missense variants
# ============================================================

AA3_TO_1 = {
    "Ala": "A", "Arg": "R", "Asn": "N", "Asp": "D", "Cys": "C",
    "Gln": "Q", "Glu": "E", "Gly": "G", "His": "H", "Ile": "I",
    "Leu": "L", "Lys": "K", "Met": "M", "Phe": "F", "Pro": "P",
    "Ser": "S", "Thr": "T", "Trp": "W", "Tyr": "Y", "Val": "V",
}

STANDARD_AA = set(AA3_TO_1.values())

PROTEIN_CHANGE_RE = re.compile(r"p\.\(?([A-Z][a-z]{2})(\d+)([A-Z][a-z]{2})\)?")

def parse_protein_change_from_name(name):
    """Return wt_aa, position, mut_aa from ClinVar Name, or None values if not simple missense."""
    if pd.isna(name):
        return None, None, None
    m = PROTEIN_CHANGE_RE.search(str(name))
    if not m:
        return None, None, None

    wt3, pos, mut3 = m.groups()
    wt = AA3_TO_1.get(wt3)
    mut = AA3_TO_1.get(mut3)

    if wt is None or mut is None:
        return None, None, None
    if wt == mut:
        return None, None, None

    return wt, int(pos), mut


def clinical_significance_to_label(sig):
    """
    Convert ClinVar clinical significance into binary label.
    Pathogenic / likely pathogenic -> 1
    Benign / likely benign -> 0
    Others, including VUS/conflicting -> None
    """
    if pd.isna(sig):
        return None

    s = str(sig).lower()

    # Remove ambiguous labels from training.
    ambiguous_terms = [
        "uncertain",
        "conflicting",
        "not provided",
        "association",
        "risk factor",
        "drug response",
        "protective",
        "affects",
        "other",
    ]
    if any(term in s for term in ambiguous_terms):
        return None

    has_path = "pathogenic" in s
    has_benign = "benign" in s

    if has_path and not has_benign:
        return 1
    if has_benign and not has_path:
        return 0
    return None


def is_vus_like(sig):
    if pd.isna(sig):
        return False
    s = str(sig).lower()
    return "uncertain" in s or "conflicting" in s


def read_target_clinvar_variants(clinvar_path, target_genes, chunksize=250_000):
    """Stream ClinVar and keep only parsed missense variants from target genes."""

    needed = [
        "#AlleleID", "Type", "Name", "GeneID", "GeneSymbol",
        "ClinicalSignificance", "ClinSigSimple", "Assembly",
        "ReviewStatus", "VariationID", "PhenotypeList",
    ]
    available = [c for c in needed if c in clinvar_header]

    frames = []
    target_genes = set(target_genes)

    reader = pd.read_csv(
        clinvar_path,
        sep="\t",
        compression="gzip",
        dtype=str,
        usecols=available,
        chunksize=chunksize,
        low_memory=False,
    )

    for chunk in tqdm(reader, desc="Filtering ClinVar chunks"):
        if "GeneSymbol" not in chunk.columns or "Name" not in chunk.columns:
            raise ValueError("ClinVar file is missing GeneSymbol or Name column.")

        chunk = chunk[chunk["GeneSymbol"].isin(target_genes)].copy()

        if "Assembly" in chunk.columns:
            chunk = chunk[chunk["Assembly"].eq("GRCh38")].copy()

        if "Type" in chunk.columns:
            chunk = chunk[chunk["Type"].str.lower().eq("single nucleotide variant")].copy()

        if chunk.empty:
            continue

        parsed = chunk["Name"].apply(parse_protein_change_from_name)
        chunk["wt_aa"] = parsed.apply(lambda x: x[0])
        chunk["position"] = parsed.apply(lambda x: x[1])
        chunk["mut_aa"] = parsed.apply(lambda x: x[2])

        chunk = chunk.dropna(subset=["wt_aa", "position", "mut_aa"]).copy()
        if chunk.empty:
            continue

        chunk["position"] = chunk["position"].astype(int)
        chunk["label"] = chunk["ClinicalSignificance"].apply(clinical_significance_to_label)
        chunk["is_vus_like"] = chunk["ClinicalSignificance"].apply(is_vus_like)

        frames.append(chunk)

    if not frames:
        raise RuntimeError("No target missense variants were found. Try adding more target genes.")

    df = pd.concat(frames, ignore_index=True)

    # Deduplicate repeated variant-condition rows.
    dedupe_cols = ["GeneSymbol", "position", "wt_aa", "mut_aa", "label"]
    df = df.drop_duplicates(subset=dedupe_cols).reset_index(drop=True)

    return df


clinvar_variants = read_target_clinvar_variants(CLINVAR_PATH, TARGET_PROTEINS.keys())

print("Parsed target missense variants:", len(clinvar_variants))
display(clinvar_variants[[
    "GeneSymbol", "Name", "ClinicalSignificance", "wt_aa", "position", "mut_aa", "label", "is_vus_like"
]].head())

print("\nLabel counts before sequence verification:")
print(clinvar_variants["label"].value_counts(dropna=False))

# ============================================================
# 5. Balance the labeled training set and keep VUS-like variants separately
# ============================================================

labeled_raw = clinvar_variants[clinvar_variants["label"].notna()].copy()
labeled_raw["label"] = labeled_raw["label"].astype(int)

vus_raw = clinvar_variants[
    clinvar_variants["label"].isna() & clinvar_variants["is_vus_like"]
].copy()

def sample_per_gene_class(df, max_n=120, seed=42):
    parts = []
    for (gene, label), group in df.groupby(["GeneSymbol", "label"]):
        n = min(len(group), max_n)
        parts.append(group.sample(n=n, random_state=seed))
    return pd.concat(parts, ignore_index=True)

labeled_sample = sample_per_gene_class(
    labeled_raw,
    max_n=MAX_VARIANTS_PER_CLASS_PER_GENE,
    seed=SEED,
)

print("Labeled sample size:", len(labeled_sample))
print(labeled_sample.groupby(["GeneSymbol", "label"]).size())

print("\nVUS-like candidates before verification:", len(vus_raw))

# ============================================================
# 6. Download UniProt protein sequence + feature annotations
# ============================================================

def fetch_uniprot_json(accession):
    url = f"https://rest.uniprot.org/uniprotkb/{accession}.json"
    r = requests.get(url, timeout=60)
    r.raise_for_status()
    return r.json()


def extract_uniprot_intervals(uniprot_json):
    """Extract protein feature intervals from UniProt JSON."""
    intervals = []
    for feat in uniprot_json.get("features", []):
        ftype = feat.get("type", "Unknown")
        desc = feat.get("description", "")

        loc = feat.get("location", {})
        start_obj = loc.get("start", {})
        end_obj = loc.get("end", {})

        start = start_obj.get("value")
        end = end_obj.get("value")

        if start is None or end is None:
            continue

        try:
            start, end = int(start), int(end)
        except Exception:
            continue

        intervals.append({
            "type": ftype,
            "description": desc,
            "start": start,
            "end": end,
        })
    return intervals


protein_info = {}

for gene, acc in TARGET_PROTEINS.items():
    print(f"Fetching UniProt: {gene} -> {acc}")
    js = fetch_uniprot_json(acc)
    sequence = js["sequence"]["value"]
    features = extract_uniprot_intervals(js)
    protein_info[gene] = {
        "accession": acc,
        "sequence": sequence,
        "length": len(sequence),
        "features": features,
    }

pd.DataFrame([
    {
        "GeneSymbol": gene,
        "UniProt": info["accession"],
        "Length": info["length"],
        "Num_features": len(info["features"]),
    }
    for gene, info in protein_info.items()
])

# ============================================================
# 7. Protein feature engineering helpers
# ============================================================

blosum62 = substitution_matrices.load("BLOSUM62")

HYDROPATHY = {
    "A": 1.8,  "R": -4.5, "N": -3.5, "D": -3.5, "C": 2.5,
    "Q": -3.5, "E": -3.5, "G": -0.4, "H": -3.2, "I": 4.5,
    "L": 3.8,  "K": -3.9, "M": 1.9,  "F": 2.8,  "P": -1.6,
    "S": -0.8, "T": -0.7, "W": -0.9, "Y": -1.3, "V": 4.2,
}

AA_MASS = {
    "A": 89.09,  "R": 174.20, "N": 132.12, "D": 133.10, "C": 121.15,
    "Q": 146.15, "E": 147.13, "G": 75.07,  "H": 155.16, "I": 131.17,
    "L": 131.17, "K": 146.19, "M": 149.21, "F": 165.19, "P": 115.13,
    "S": 105.09, "T": 119.12, "W": 204.23, "Y": 181.19, "V": 117.15,
}

CHARGE_CLASS = {
    "D": "negative", "E": "negative",
    "K": "positive", "R": "positive", "H": "positive",
}

DOMAIN_LIKE_TYPES = {
    "Domain", "Repeat", "Zinc finger", "DNA binding",
    "Nucleotide binding", "Region", "Compositional bias",
}

ACTIVE_BINDING_TYPES = {
    "Active site", "Binding site", "Site", "Metal binding",
    "Calcium binding", "Modified residue",
}

MEMBRANE_TYPES = {
    "Transmembrane", "Topological domain", "Intramembrane",
}


def blosum_score(a, b):
    try:
        return float(blosum62[a, b])
    except Exception:
        try:
            return float(blosum62[b, a])
        except Exception:
            return np.nan


def charge_group(aa):
    return CHARGE_CLASS.get(aa, "neutral")


def feature_flags_at_position(intervals, pos):
    covering = [f for f in intervals if f["start"] <= pos <= f["end"]]
    covering_types = {f["type"] for f in covering}

    return {
        "in_any_uniprot_feature": int(len(covering) > 0),
        "in_domain_like_feature": int(len(covering_types & DOMAIN_LIKE_TYPES) > 0),
        "in_active_or_binding_feature": int(len(covering_types & ACTIVE_BINDING_TYPES) > 0),
        "in_membrane_feature": int(len(covering_types & MEMBRANE_TYPES) > 0),
        "uniprot_feature_count": len(covering),
        "covering_feature_types": ";".join(sorted(covering_types)),
    }


def make_mutation_window(sequence, pos, wt_aa, mut_aa, radius=255):
    """
    Build local wild-type and mutant sequence windows around a 1-based mutation position.
    Returns wt_window, mut_window, local_pos, window_start, window_end.
    """
    pos = int(pos)
    if sequence[pos - 1] != wt_aa:
        raise ValueError(f"WT mismatch at position {pos}: sequence has {sequence[pos-1]}, expected {wt_aa}")

    start = max(1, pos - radius)
    end = min(len(sequence), pos + radius)

    wt_window = sequence[start - 1:end]
    local_pos = pos - start + 1

    mut_list = list(wt_window)
    mut_list[local_pos - 1] = mut_aa
    mut_window = "".join(mut_list)

    return wt_window, mut_window, local_pos, start, end


def annotate_variants_with_sequence_and_uniprot(df, protein_info, radius=255):
    """Verify canonical sequence coordinates, build windows, and add protein/domain features."""

    rows = []
    mismatch_count = 0
    out_of_range_count = 0

    for _, row in tqdm(df.iterrows(), total=len(df), desc="Verifying sequence positions"):
        gene = row["GeneSymbol"]
        if gene not in protein_info:
            continue

        seq = protein_info[gene]["sequence"]
        pos = int(row["position"])
        wt = row["wt_aa"]
        mut = row["mut_aa"]

        if pos < 1 or pos > len(seq):
            out_of_range_count += 1
            continue

        if seq[pos - 1] != wt:
            mismatch_count += 1
            continue

        wt_window, mut_window, local_pos, win_start, win_end = make_mutation_window(
            sequence=seq,
            pos=pos,
            wt_aa=wt,
            mut_aa=mut,
            radius=radius,
        )

        flags = feature_flags_at_position(protein_info[gene]["features"], pos)

        new_row = row.to_dict()
        new_row.update({
            "uniprot_accession": protein_info[gene]["accession"],
            "protein_length": len(seq),
            "norm_position": pos / len(seq),
            "wt_window": wt_window,
            "mut_window": mut_window,
            "local_pos": local_pos,
            "window_start": win_start,
            "window_end": win_end,
            "window_length": len(wt_window),
            "blosum62": blosum_score(wt, mut),
            "hydropathy_delta": HYDROPATHY[mut] - HYDROPATHY[wt],
            "abs_hydropathy_delta": abs(HYDROPATHY[mut] - HYDROPATHY[wt]),
            "mass_delta": AA_MASS[mut] - AA_MASS[wt],
            "abs_mass_delta": abs(AA_MASS[mut] - AA_MASS[wt]),
            "charge_changed": int(charge_group(wt) != charge_group(mut)),
            "to_proline": int(mut == "P"),
            "from_glycine": int(wt == "G"),
            "to_glycine": int(mut == "G"),
        })
        new_row.update(flags)
        rows.append(new_row)

    verified = pd.DataFrame(rows)

    print("Kept variants:", len(verified))
    print("Dropped due to WT mismatch:", mismatch_count)
    print("Dropped due to out-of-range position:", out_of_range_count)

    return verified


labeled_verified = annotate_variants_with_sequence_and_uniprot(
    labeled_sample,
    protein_info,
    radius=WINDOW_RADIUS,
)

print("\nVerified labeled data shape:", labeled_verified.shape)
print(labeled_verified.groupby(["GeneSymbol", "label"]).size())
display(labeled_verified.head())

# ============================================================
# 8. Load ESM-2 model
# ============================================================

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
esm_model = AutoModel.from_pretrained(MODEL_NAME)
esm_model.to(device)
esm_model.eval()

print("Loaded:", MODEL_NAME)
print("Hidden size:", esm_model.config.hidden_size)

# ============================================================
# 9. ESM-2 embedding extraction
# ============================================================

def embed_sequence_windows(sequences, local_positions, batch_size=8):
    """
    Return mean-pooled and mutation-site embeddings for each sequence window.

    For ESM tokenization:
    token index 0 is a special token.
    sequence residue i, using 1-based local position, is token index i.
    """
    mean_embeddings = []
    site_embeddings = []

    for start in tqdm(range(0, len(sequences), batch_size), desc="ESM embedding batches"):
        batch_seqs = list(sequences[start:start + batch_size])
        batch_pos = list(local_positions[start:start + batch_size])

        enc = tokenizer(
            batch_seqs,
            return_tensors="pt",
            padding=True,
            truncation=True,
            max_length=MAX_TOKENS,
        )
        enc = {k: v.to(device) for k, v in enc.items()}

        with torch.no_grad():
            outputs = esm_model(**enc)
            hidden = outputs.last_hidden_state.detach().cpu()

        for j, seq in enumerate(batch_seqs):
            # Exclude special tokens; use only residue embeddings.
            L = min(len(seq), MAX_TOKENS - 2)
            residue_embeddings = hidden[j, 1:L + 1, :]
            mean_emb = residue_embeddings.mean(dim=0).numpy()

            site_index = min(int(batch_pos[j]), L)
            site_emb = hidden[j, site_index, :].numpy()

            mean_embeddings.append(mean_emb)
            site_embeddings.append(site_emb)

    return np.vstack(mean_embeddings), np.vstack(site_embeddings)


def cosine_distance(a, b):
    denom = (np.linalg.norm(a) * np.linalg.norm(b)) + 1e-12
    return 1.0 - float(np.dot(a, b) / denom)


def add_esm_change_features(df, cache_prefix="/content/labeled"):
    """Compute WT-vs-mutant ESM embedding-change features."""
    df = df.reset_index(drop=True).copy()

    cache_csv = f"{cache_prefix}_with_esm_features.csv"
    if os.path.exists(cache_csv):
        print("Loading cached ESM features:", cache_csv)
        return pd.read_csv(cache_csv)

    n = len(df)

    all_sequences = df["wt_window"].tolist() + df["mut_window"].tolist()
    all_positions = df["local_pos"].tolist() + df["local_pos"].tolist()

    mean_embs, site_embs = embed_sequence_windows(
        all_sequences,
        all_positions,
        batch_size=BATCH_SIZE,
    )

    wt_mean = mean_embs[:n]
    mut_mean = mean_embs[n:]
    wt_site = site_embs[:n]
    mut_site = site_embs[n:]

    mean_cos = []
    mean_l2 = []
    site_cos = []
    site_l2 = []
    site_abs_delta_mean = []
    mean_abs_delta_mean = []

    for i in range(n):
        mean_cos.append(cosine_distance(wt_mean[i], mut_mean[i]))
        mean_l2.append(float(np.linalg.norm(mut_mean[i] - wt_mean[i])))

        site_cos.append(cosine_distance(wt_site[i], mut_site[i]))
        site_l2.append(float(np.linalg.norm(mut_site[i] - wt_site[i])))

        site_abs_delta_mean.append(float(np.mean(np.abs(mut_site[i] - wt_site[i]))))
        mean_abs_delta_mean.append(float(np.mean(np.abs(mut_mean[i] - wt_mean[i]))))

    df["esm_mean_cosine_distance"] = mean_cos
    df["esm_mean_l2_distance"] = mean_l2
    df["esm_site_cosine_distance"] = site_cos
    df["esm_site_l2_distance"] = site_l2
    df["esm_site_abs_delta_mean"] = site_abs_delta_mean
    df["esm_mean_abs_delta_mean"] = mean_abs_delta_mean

    df.to_csv(cache_csv, index=False)
    print("Saved:", cache_csv)

    return df


features_df = add_esm_change_features(labeled_verified, cache_prefix="/content/labeled")

print("Final feature table:", features_df.shape)
display(features_df.head())

# ============================================================
# 10.A Train/test split and model comparison
# ============================================================

bio_domain_features = [
    "norm_position",
    "protein_length",
    "window_length",
    "blosum62",
    "hydropathy_delta",
    "abs_hydropathy_delta",
    "mass_delta",
    "abs_mass_delta",
    "charge_changed",
    "to_proline",
    "from_glycine",
    "to_glycine",
    "in_any_uniprot_feature",
    "in_domain_like_feature",
    "in_active_or_binding_feature",
    "in_membrane_feature",
    "uniprot_feature_count",
]

esm_features = [
    "esm_mean_cosine_distance",
    "esm_mean_l2_distance",
    "esm_site_cosine_distance",
    "esm_site_l2_distance",
    "esm_site_abs_delta_mean",
    "esm_mean_abs_delta_mean",
]

all_features = bio_domain_features + esm_features

# Keep rows with valid labels.
model_df = features_df.dropna(subset=["label"]).copy()
model_df["label"] = model_df["label"].astype(int)

X = model_df[all_features].copy()
y = model_df["label"].copy()

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.25,
    stratify=y,
    random_state=SEED,
)

print("Train:", X_train.shape, "Test:", X_test.shape)
print("Train label balance:")
print(y_train.value_counts(normalize=True))
print("Test label balance:")
print(y_test.value_counts(normalize=True))


def build_logreg():
    return Pipeline([
        ("imputer", SimpleImputer(strategy="median")),
        ("scaler", StandardScaler()),
        ("clf", LogisticRegression(
            max_iter=3000,
            class_weight="balanced",
            random_state=SEED,
        )),
    ])


def build_rf():
    return Pipeline([
        ("imputer", SimpleImputer(strategy="median")),
        ("clf", RandomForestClassifier(
            n_estimators=300,
            max_depth=None,
            min_samples_leaf=2,
            class_weight="balanced",
            random_state=SEED,
            n_jobs=-1,
        )),
    ])


def evaluate_model(model_name, feature_cols, estimator):
    estimator.fit(X_train[feature_cols], y_train)

    pred = estimator.predict(X_test[feature_cols])
    if hasattr(estimator, "predict_proba"):
        prob = estimator.predict_proba(X_test[feature_cols])[:, 1]
    else:
        prob = pred

    precision, recall, f1, _ = precision_recall_fscore_support(
        y_test,
        pred,
        average="binary",
        zero_division=0,
    )

    result = {
        "model_name": model_name,
        "n_features": len(feature_cols),
        "accuracy": accuracy_score(y_test, pred),
        "precision_pathogenic": precision,
        "recall_pathogenic": recall,
        "f1_pathogenic": f1,
        "roc_auc": roc_auc_score(y_test, prob),
    }

    return estimator, result


experiments = [
    ("Bio/domain only | LogisticRegression", bio_domain_features, build_logreg()),
    ("ESM only | LogisticRegression", esm_features, build_logreg()),
    ("ESM + bio/domain | LogisticRegression", all_features, build_logreg()),
    ("Bio/domain only | RandomForest", bio_domain_features, build_rf()),
    ("ESM only | RandomForest", esm_features, build_rf()),
    ("ESM + bio/domain | RandomForest", all_features, build_rf()),
]

trained_models = {}
results = []

for name, cols, estimator in experiments:
    fitted, result = evaluate_model(name, cols, estimator)
    trained_models[name] = {
        "model": fitted,
        "features": cols,
        "result": result,
    }
    results.append(result)

results_df = pd.DataFrame(results)

# Select the best model using a practical pathogenicity-screening score.
# This favors the model that performs best on accuracy, pathogenic recall, and F1-score.
selection_metrics = [
    "accuracy",
    "recall_pathogenic",
    "f1_pathogenic",
]

results_df["selection_score"] = results_df[selection_metrics].mean(axis=1)

# Sort by practical score first.
# If two models tie, use ROC-AUC as the secondary tie-breaker.
results_df = results_df.sort_values(
    ["selection_score", "roc_auc"],
    ascending=[False, False]
)

display(results_df)
results_df.to_csv("/content/model_comparison_results.csv", index=False)

best_name = results_df.iloc[0]["model_name"]
best_model = trained_models[best_name]["model"]
best_features = trained_models[best_name]["features"]

print("Best model selected using practical screening score:", best_name)
print("Selection metrics used:", selection_metrics)
print("Features used:", best_features)

# ============================================================
# 10B. Hyperparameter Sensitivity + Learning/Convergence Curves
# ============================================================

from sklearn.model_selection import train_test_split, StratifiedKFold, learning_curve
from sklearn.metrics import accuracy_score, precision_recall_fscore_support, roc_auc_score
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


# ------------------------------------------------------------
# A. Create internal train/validation split from the training set
# ------------------------------------------------------------
# The original test set remains untouched.
# Hyperparameter checks are done using train_core and validation set.

X_train_core, X_val, y_train_core, y_val = train_test_split(
    X_train,
    y_train,
    test_size=0.20,
    stratify=y_train,
    random_state=SEED,
)

print("Train-core:", X_train_core.shape)
print("Validation:", X_val.shape)
print("Held-out test:", X_test.shape)


# ------------------------------------------------------------
# B. Helper evaluation function
# ------------------------------------------------------------

def evaluate_on_split(estimator, feature_cols, X_tr, y_tr, X_ev, y_ev):
    estimator.fit(X_tr[feature_cols], y_tr)

    pred = estimator.predict(X_ev[feature_cols])

    if hasattr(estimator, "predict_proba"):
        prob = estimator.predict_proba(X_ev[feature_cols])[:, 1]
    else:
        prob = pred

    precision, recall, f1, _ = precision_recall_fscore_support(
        y_ev,
        pred,
        average="binary",
        zero_division=0,
    )

    return {
        "accuracy": accuracy_score(y_ev, pred),
        "precision_pathogenic": precision,
        "recall_pathogenic": recall,
        "f1_pathogenic": f1,
        "roc_auc": roc_auc_score(y_ev, prob),
    }


# ------------------------------------------------------------
# C. Feature-set definitions
# ------------------------------------------------------------

feature_sets = {
    "Bio/domain only": bio_domain_features,
    "ESM only": esm_features,
    "ESM + bio/domain": all_features,
}


# ------------------------------------------------------------
# D. Hyperparameter sensitivity for Logistic Regression
# ------------------------------------------------------------
# Hyperparameter varied: C
# C controls regularization strength.
# Smaller C = stronger regularization.
# Larger C = weaker regularization.

logreg_C_values = [0.01, 0.1, 1.0, 10.0]

hyperparam_results = []

for feature_set_name, feature_cols in feature_sets.items():
    for C_value in logreg_C_values:

        estimator = Pipeline([
            ("imputer", SimpleImputer(strategy="median")),
            ("scaler", StandardScaler()),
            ("clf", LogisticRegression(
                C=C_value,
                max_iter=3000,
                class_weight="balanced",
                random_state=SEED,
            )),
        ])

        val_metrics = evaluate_on_split(
            estimator,
            feature_cols,
            X_train_core,
            y_train_core,
            X_val,
            y_val,
        )

        row = {
            "algorithm": "LogisticRegression",
            "feature_set": feature_set_name,
            "hyperparameter": "C",
            "hyperparameter_value": C_value,
            **val_metrics,
        }

        hyperparam_results.append(row)


# ------------------------------------------------------------
# E. Hyperparameter sensitivity for RandomForest
# ------------------------------------------------------------
# Hyperparameter varied: n_estimators
# n_estimators = number of trees in the forest.

rf_n_estimators_values = [100, 200, 300, 500]

for feature_set_name, feature_cols in feature_sets.items():
    for n_tree in rf_n_estimators_values:

        estimator = Pipeline([
            ("imputer", SimpleImputer(strategy="median")),
            ("clf", RandomForestClassifier(
                n_estimators=n_tree,
                max_depth=None,
                min_samples_leaf=2,
                class_weight="balanced",
                random_state=SEED,
                n_jobs=-1,
            )),
        ])

        val_metrics = evaluate_on_split(
            estimator,
            feature_cols,
            X_train_core,
            y_train_core,
            X_val,
            y_val,
        )

        row = {
            "algorithm": "RandomForest",
            "feature_set": feature_set_name,
            "hyperparameter": "n_estimators",
            "hyperparameter_value": n_tree,
            **val_metrics,
        }

        hyperparam_results.append(row)


hyperparam_results_df = pd.DataFrame(hyperparam_results)

# Practical selection score used in the project
selection_metrics = ["accuracy", "recall_pathogenic", "f1_pathogenic"]
hyperparam_results_df["selection_score"] = hyperparam_results_df[selection_metrics].mean(axis=1)

hyperparam_results_df = hyperparam_results_df.sort_values(
    ["feature_set", "algorithm", "selection_score"],
    ascending=[True, True, False],
)

display(hyperparam_results_df)

hyperparam_results_df.to_csv(
    "/content/hyperparameter_sensitivity_results.csv",
    index=False,
)

print("Saved: /content/hyperparameter_sensitivity_results.csv")

# ============================================================
# 10C. Plot hyperparameter sensitivity results
# ============================================================

# Plot 1: Logistic Regression C values for all feature sets
plt.figure(figsize=(9, 5))

for feature_set_name in feature_sets.keys():
    temp = hyperparam_results_df[
        (hyperparam_results_df["algorithm"] == "LogisticRegression") &
        (hyperparam_results_df["feature_set"] == feature_set_name)
    ].sort_values("hyperparameter_value")

    plt.plot(
        temp["hyperparameter_value"],
        temp["f1_pathogenic"],
        marker="o",
        label=feature_set_name,
    )

plt.xscale("log")
plt.xlabel("C value")
plt.ylabel("Validation F1-score")
plt.title("Logistic Regression hyperparameter sensitivity")
plt.legend()
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.savefig("/content/logistic_regression_hyperparameter_sensitivity.png", dpi=300)
plt.show()


# Plot 2: RandomForest n_estimators values for all feature sets
plt.figure(figsize=(9, 5))

for feature_set_name in feature_sets.keys():
    temp = hyperparam_results_df[
        (hyperparam_results_df["algorithm"] == "RandomForest") &
        (hyperparam_results_df["feature_set"] == feature_set_name)
    ].sort_values("hyperparameter_value")

    plt.plot(
        temp["hyperparameter_value"],
        temp["f1_pathogenic"],
        marker="o",
        label=feature_set_name,
    )

plt.xlabel("Number of trees / n_estimators")
plt.ylabel("Validation F1-score")
plt.title("RandomForest hyperparameter sensitivity")
plt.legend()
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.savefig("/content/randomforest_hyperparameter_sensitivity.png", dpi=300)
plt.show()

print("Saved:")
print("/content/logistic_regression_hyperparameter_sensitivity.png")
print("/content/randomforest_hyperparameter_sensitivity.png")

# ============================================================
# 10D. Learning / convergence curves
# ============================================================

cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=SEED,
)

train_sizes = np.linspace(0.2, 1.0, 5)


def plot_learning_curve_for_model(estimator, feature_cols, title, output_path):
    train_sizes_abs, train_scores, val_scores = learning_curve(
        estimator=estimator,
        X=X_train[feature_cols],
        y=y_train,
        train_sizes=train_sizes,
        cv=cv,
        scoring="f1",
        n_jobs=-1,
        shuffle=True,
        random_state=SEED,
    )

    train_mean = train_scores.mean(axis=1)
    train_std = train_scores.std(axis=1)
    val_mean = val_scores.mean(axis=1)
    val_std = val_scores.std(axis=1)

    plt.figure(figsize=(8, 5))

    plt.plot(
        train_sizes_abs,
        train_mean,
        marker="o",
        label="Training F1",
    )

    plt.fill_between(
        train_sizes_abs,
        train_mean - train_std,
        train_mean + train_std,
        alpha=0.15,
    )

    plt.plot(
        train_sizes_abs,
        val_mean,
        marker="o",
        label="Validation F1",
    )

    plt.fill_between(
        train_sizes_abs,
        val_mean - val_std,
        val_mean + val_std,
        alpha=0.15,
    )

    plt.xlabel("Number of training examples")
    plt.ylabel("F1-score")
    plt.title(title)
    plt.legend()
    plt.grid(True, alpha=0.3)
    plt.tight_layout()
    plt.savefig(output_path, dpi=300)
    plt.show()

    curve_df = pd.DataFrame({
        "training_examples": train_sizes_abs,
        "training_f1_mean": train_mean,
        "training_f1_std": train_std,
        "validation_f1_mean": val_mean,
        "validation_f1_std": val_std,
    })

    return curve_df


# Proposed model: ESM + Bio/domain RandomForest
proposed_rf_estimator = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("clf", RandomForestClassifier(
        n_estimators=300,
        max_depth=None,
        min_samples_leaf=2,
        class_weight="balanced",
        random_state=SEED,
        n_jobs=-1,
    )),
])

proposed_learning_curve_df = plot_learning_curve_for_model(
    estimator=proposed_rf_estimator,
    feature_cols=all_features,
    title="Learning curve: proposed ESM + Bio/domain RandomForest",
    output_path="/content/learning_curve_proposed_esm_biodomain_rf.png",
)

display(proposed_learning_curve_df)

proposed_learning_curve_df.to_csv(
    "/content/learning_curve_proposed_esm_biodomain_rf.csv",
    index=False,
)


# Optional comparison: Bio/domain only RandomForest
bio_rf_estimator = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("clf", RandomForestClassifier(
        n_estimators=300,
        max_depth=None,
        min_samples_leaf=2,
        class_weight="balanced",
        random_state=SEED,
        n_jobs=-1,
    )),
])

bio_learning_curve_df = plot_learning_curve_for_model(
    estimator=bio_rf_estimator,
    feature_cols=bio_domain_features,
    title="Learning curve: Bio/domain only RandomForest",
    output_path="/content/learning_curve_biodomain_rf.png",
)

bio_learning_curve_df.to_csv(
    "/content/learning_curve_biodomain_rf.csv",
    index=False,
)


# Optional comparison: ESM only RandomForest
esm_rf_estimator = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("clf", RandomForestClassifier(
        n_estimators=300,
        max_depth=None,
        min_samples_leaf=2,
        class_weight="balanced",
        random_state=SEED,
        n_jobs=-1,
    )),
])

esm_learning_curve_df = plot_learning_curve_for_model(
    estimator=esm_rf_estimator,
    feature_cols=esm_features,
    title="Learning curve: ESM only RandomForest",
    output_path="/content/learning_curve_esm_rf.png",
)

esm_learning_curve_df.to_csv(
    "/content/learning_curve_esm_rf.csv",
    index=False,
)

print("Saved:")
print("/content/learning_curve_proposed_esm_biodomain_rf.png")
print("/content/learning_curve_biodomain_rf.png")
print("/content/learning_curve_esm_rf.png")
print("/content/learning_curve_proposed_esm_biodomain_rf.csv")
print("/content/learning_curve_biodomain_rf.csv")
print("/content/learning_curve_esm_rf.csv")

# ============================================================
# 10E. Download outputs from Colab
# ============================================================

from google.colab import files

files.download("/content/hyperparameter_sensitivity_results.csv")
files.download("/content/logistic_regression_hyperparameter_sensitivity.png")
files.download("/content/randomforest_hyperparameter_sensitivity.png")
files.download("/content/learning_curve_proposed_esm_biodomain_rf.png")
files.download("/content/learning_curve_biodomain_rf.png")
files.download("/content/learning_curve_esm_rf.png")
files.download("/content/learning_curve_proposed_esm_biodomain_rf.csv")

# ============================================================
# 11. Detailed evaluation of best model
# ============================================================

best_pred = best_model.predict(X_test[best_features])
best_prob = best_model.predict_proba(X_test[best_features])[:, 1]

print(classification_report(
    y_test,
    best_pred,
    target_names=["Benign", "Pathogenic"],
    zero_division=0,
))

ConfusionMatrixDisplay.from_predictions(
    y_test,
    best_pred,
    display_labels=["Benign", "Pathogenic"],
)
plt.title(f"Confusion matrix: {best_name}")
plt.tight_layout()
plt.savefig("/content/confusion_matrix.png", dpi=200)
plt.show()

RocCurveDisplay.from_estimator(best_model, X_test[best_features], y_test)
plt.title(f"ROC curve: {best_name}")
plt.tight_layout()
plt.savefig("/content/roc_curve.png", dpi=200)
plt.show()

# ============================================================
# 12. Interpretability: coefficients or feature importance
# ============================================================

def get_feature_importance_or_coefficients(model_entry):
    model = model_entry["model"]
    cols = model_entry["features"]

    clf = model.named_steps["clf"]

    if hasattr(clf, "feature_importances_"):
        values = clf.feature_importances_
        kind = "random_forest_importance"
    elif hasattr(clf, "coef_"):
        values = clf.coef_[0]
        kind = "logistic_regression_coefficient"
    else:
        return None

    out = pd.DataFrame({
        "feature": cols,
        kind: values,
        "abs_value": np.abs(values),
    }).sort_values("abs_value", ascending=False)

    return out


importance_df = get_feature_importance_or_coefficients(trained_models[best_name])
if importance_df is not None:
    display(importance_df.head(20))
    importance_df.to_csv("/content/best_model_feature_importance.csv", index=False)

    top = importance_df.head(15).iloc[::-1]
    plt.figure(figsize=(8, 5))
    plt.barh(top["feature"], top.iloc[:, 1])
    plt.title(f"Top features: {best_name}")
    plt.xlabel("Importance / coefficient")
    plt.tight_layout()
    plt.savefig("/content/top_features.png", dpi=200)
    plt.show()
else:
    print("No importance/coefficient available for this model.")

# ============================================================
# 13. VUS-style case study
# ============================================================

# Sample VUS-like variants. These are not used for training.
if len(vus_raw) > 0:
    vus_sample = vus_raw.sample(
        n=min(len(vus_raw), MAX_VUS_CASE_STUDY_VARIANTS),
        random_state=SEED,
    )

    vus_verified = annotate_variants_with_sequence_and_uniprot(
        vus_sample,
        protein_info,
        radius=WINDOW_RADIUS,
    )

    print("Verified VUS-like variants:", len(vus_verified))

    if len(vus_verified) > 0:
        vus_features = add_esm_change_features(vus_verified, cache_prefix="/content/vus")

        vus_features["predicted_pathogenic_probability"] = best_model.predict_proba(
            vus_features[best_features]
        )[:, 1]

        vus_features["predicted_class"] = np.where(
            vus_features["predicted_pathogenic_probability"] >= 0.5,
            "Predicted pathogenic-like",
            "Predicted benign-like",
        )

        case_study_cols = [
            "GeneSymbol",
            "Name",
            "ClinicalSignificance",
            "wt_aa",
            "position",
            "mut_aa",
            "predicted_pathogenic_probability",
            "predicted_class",
            "in_domain_like_feature",
            "in_active_or_binding_feature",
            "covering_feature_types",
            "PhenotypeList",
        ]
        case_study_cols = [c for c in case_study_cols if c in vus_features.columns]

        vus_ranked = vus_features.sort_values(
            "predicted_pathogenic_probability",
            ascending=False,
        )[case_study_cols]

        display(vus_ranked.head(20))
        vus_ranked.to_csv("/content/vus_case_study_predictions.csv", index=False)
        print("Saved /content/vus_case_study_predictions.csv")
    else:
        print("No VUS-like variants survived canonical sequence verification.")
else:
    print("No VUS-like candidates found in the selected genes.")

# ============================================================
# 14. Save final outputs
# ============================================================

features_df.to_csv("/content/final_training_features.csv", index=False)

print("Saved files:")
print("/content/final_training_features.csv")
print("/content/model_comparison_results.csv")
print("/content/confusion_matrix.png")
print("/content/roc_curve.png")
print("/content/top_features.png, if available")
print("/content/vus_case_study_predictions.csv, if VUS variants were available")

#In Colab, uncomment these lines if you want to download the outputs:
# from google.colab import files
# files.download("/content/final_training_features.csv")
# files.download("/content/model_comparison_results.csv")
# files.download("/content/confusion_matrix.png")
# files.download("/content/roc_curve.png")
# files.download("/content/vus_case_study_predictions.csv")

